// GENERATED by scripts/gen-protocol-types.mjs from pulsevault-mieweb/protocol/schemas/
// (upload protocol 2.1) and package.json `pulseProtocol`. Do not edit: change the
// schema in pulsevault and bump the submodule, or change package.json, then run
// `node scripts/gen-protocol-types.mjs`.

/** The upload-protocol majors this app speaks: package.json `pulseProtocol`. */
export const APP_PROTOCOL: { min: number; max: number } = { min: 1, max: 2 };

/**
 * Unauthenticated discovery (PROTOCOL.md §2). A client reads it before pairing and pairs only if its protocol range overlaps [minSupportedVersion, maxSupportedVersion]. Clients must ignore fields they don't recognize.
 */
export interface CapabilitiesResponse {
  /**
   * Protocol major this server implements. Also sent as the `Protocol-Version` header on every response.
   */
  protocolVersion: number;
  /**
   * Spec revision this server implements, `major.minor`. The minor counts additions older clients can ignore.
   */
  protocolRevision: string;
  /**
   * Oldest protocol major this server accepts. Clients whose newest protocol is older get 426 Upgrade Required.
   */
  minSupportedVersion: number;
  /**
   * Newest protocol major this server accepts.
   */
  maxSupportedVersion: number;
  /**
   * Artifact kinds this server accepts.
   */
  kinds: ('video' | 'project' | 'captions' | 'thumbnail')[];
  /**
   * Allowed file extensions per kind, lowercase with the leading dot.
   */
  allowedExtensions: {
    [k: string]: string[] | undefined;
  };
  /**
   * Largest artifact the server accepts, in bytes.
   */
  maxUploadSize: number;
  /**
   * Checksum algorithms accepted in `Upload-Metadata.checksum`.
   */
  checksum: {
    algorithms: string[];
  };
}

/**
 * The query parameters of a `pulsecam://?…` pairing link (PROTOCOL.md §3), as built by `buildUploadLink`. Clients must ignore parameters they don't recognize.
 */
export interface DeepLinkParams {
  /**
   * Link format version. A client refuses a link whose `v` it doesn't know.
   */
  v: '1';
  /**
   * The artifact the pairing is for: the video's id. Related artifacts declare it as `relatedTo`.
   */
  artifactId: string;
  /**
   * Base URL of the server, including its path prefix (e.g. `https://vault.example.org/pulsevault`). The client builds every request as `${server}/<path>`.
   */
  server: string;
  /**
   * Optional credential the client sends as `Authorization: Bearer`. Typically a capability token (capability-token.schema.json).
   */
  token?: string;
}

/**
 * The decoded `Upload-Metadata` keys a client sends when it creates an upload (PROTOCOL.md §4). Values are strings, base64-encoded on the wire. Servers ignore keys they don't recognize.
 */
export interface UploadMetadata {
  /**
   * The artifact's id. For the video it's the pairing link's `artifactId`; related artifacts use a fresh UUID. Legacy aliases `videoid` and `projectid` are still accepted.
   */
  artifactId: string;
  /**
   * Original file name. Its extension must be allowed for `kind` (see `/capabilities`).
   */
  filename: string;
  /**
   * Artifact kind. Defaults to `video`.
   */
  kind?: 'video' | 'project' | 'captions' | 'thumbnail';
  /**
   * The artifact this one belongs to: the video, for its captions, beat manifest and thumbnail. A capability token for the video also authorizes artifacts related to it.
   */
  relatedTo?: string;
  /**
   * `<algorithm>:<hex digest>` of the finished file, verified by servers that check checksums.
   */
  checksum?: string;
  /**
   * Display title (the draft name), sent on the video. Display-only; servers trim and cap it.
   */
  name?: string;
  /**
   * Since 2.1. Version of the app that uploaded it, e.g. `2.1.0 (45)`. Stored with the artifact. Display-only; servers trim and cap it.
   */
  appVersion?: string;
}

/**
 * The `kind: project` artifact (e.g. `<draftId>-beats.pulse`) related to a pulse's video (PROTOCOL.md §8). A beat is a timestamp range inside the video: where one recorded clip starts and ends. Beats are contiguous and sum to `durationMs`.
 */
export interface BeatManifest {
  /**
   * Manifest format version.
   */
  version: 1;
  /**
   * Identifies the document.
   */
  type: 'beat-manifest';
  /**
   * True duration of the video, in milliseconds.
   */
  durationMs: number;
  /**
   * One entry per recorded clip, in play order.
   */
  beats: {
    /**
     * The recorded clip's local id on the capturing device.
     */
    segmentId: string;
    /**
     * 0-based position of the clip in the video.
     */
    order: number;
    /**
     * Where the clip starts in the video, in milliseconds.
     */
    startMs: number;
    /**
     * Where the clip ends; equals the next beat's `startMs`.
     */
    endMs: number;
  }[];
}

/**
 * The claims inside a capability token (PROTOCOL.md §5.4). The token is `base64url(JSON claims).signature`, HMAC-signed by the issuing deployment. It authorizes the artifact it names and any artifact whose `relatedTo` is that artifact.
 */
export interface CapabilityTokenClaims {
  /**
   * The artifact the token is for (the pulse's video).
   */
  artifactId: string;
  /**
   * Issued at, in seconds since the Unix epoch.
   */
  iat: number;
  /**
   * Expires at, in seconds since the Unix epoch.
   */
  exp: number;
  /**
   * Id of the signing key, so a deployment can rotate secrets.
   */
  kid: string;
  /**
   * The issuing deployment. A token from another issuer is rejected.
   */
  issuer: string;
}

/**
 * Since 2.1. Optional header a client sends on every request to say what it is and which protocol majors it speaks (PROTOCOL.md §7), e.g. `Pulse/2.1.0 (45; ios); protocol=1-2`. A server answers 426 Upgrade Required on uploads and artifacts when the client's newest protocol is older than its oldest. Without the header, nothing changes.
 */
export type PulseClientHeader = string;
