# GitHub Pages Configuration for Pulse App Website

# Site settings
title: "Pulse - Institutional Knowledge Sharing Platform"
description: "Secure institutional knowledge sharing through short-form video content. Create professional training documentation, capture institutional procedures, and share knowledge across your organization with enterprise-grade security."
url: "https://mieweb.github.io"
baseurl: "/pulse"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _redirects

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "Pulse Institutional Knowledge Sharing Team"
social:
  name: "Pulse - Institutional Knowledge Sharing Platform"
  links:
    - "https://apps.apple.com/app/pulse-video-recorder/id6748621024"
    - "https://github.com/mieweb/pulse"

# Analytics (optional - add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X

# Comments (optional - add your Disqus shortname)
# disqus:
#   shortname: your-disqus-shortname
